### ISSUE TITLE
Problem with prefabs on clients

### ISSUE THREAD

**Issue by aviv0099** [ayellowpaper/SerializedDictionary#2]
you will get exceptions if you have script with a dictionary attached to a prefab, when you instantiate it for 2+ times, you will get duplicate keys exception, how to fix:

In SerializedDictionary.cs
In OnBeforeSerialize() I added _serializedList.Clear(); for clients before the loop

because if you create game objects from prefabs the _serializedList will keep growing and you will have duplicated keys -> exceptions

**Comment by MJRamon** [comment]
Can we get and update with fix, please? @ayellowpaper

**Comment by fullcorder** [comment]
same issue

**Comment by ayellowpaper** [comment]
I'm not really maintaining this branch anymore. Use the assetstore branch instead or get it directly from the [assetstore](https://assetstore.unity.com/packages/tools/utilities/serialized-dictionary-243052).

**Comment by aviv0099** [comment]
I can confirm, it was fixed in the asset store version
